name: Deploy
on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  lint:
    uses: "./.github/workflows/lint.yml"

  docker_publish:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Publish docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
